#cloud-config
users:
  - name: ubuntu
    groups:
      - sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: $6$gcF0unIinfwKORae$uuErtxZVkjS042VC5yoqm85wFhBgpxRbuUoCvcezM6cNraj21bR84YxNpfQc8lZ6rx1VCAhRM/6MIpMgzf2fA/
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFyP6QlXita25X3MtQ/+EVGoWcDHb98ZN9tTB9Mvap7n trapezia@trapezia-VMware-Virtual-Platform
